import { Header } from '@/components/layout/Header'
import TanstackProvider from '@/providers/TanstackProvider'
import ZustandProvider from '@/providers/ZustandProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

const circular_std_book = localFont({
  src: [
    {
      path: '../../public/fonts/CircularStd-Book.ttf',
      weight: '450',
    },
    {
      path: '../../public/fonts/CircularStd-Medium.ttf',
      weight: '500',
    },
    {
      path: '../../public/fonts/CircularStd-Bold.ttf',
      weight: '700',
    },
  ],
  variable: '--font-circular-std',
})

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Desafio Just Travel',
  description: 'Generated by create next app',
  icons: { icon: '/icon.png' },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${circular_std_book.variable} ${inter.variable} bg-body`}
      >
        <TanstackProvider>
          <ZustandProvider>
            <Header />
            {children}
          </ZustandProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}
